<?php
/**
 * 测试头像上传
 * 1. 构建测试账号
 * 2. 生成阿里云访问token
 * 3. 无法在这里验证token的可用性，只好冒烟看一下大概了
 * 4. 清理测试账号
 */
namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class UserTest extends TestCase
{
    protected $token_obj;
    public function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->token_obj = parent::createTestUserToken();
    }

    public function tearDown() {
        parent::eraseTestUser($this->token_obj->user_id);
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testAvatar()
    {
        $token = $this->token_obj->token;
        $response = $this->json("get", route("user.avatar_sign"), compact('token'));
        $response->assertStatus(200);
        $result = $response->json();
        $this->assertNotEmpty($result["data"]["signature"]);
        var_dump($result);
    }
}
