version: "2"
services:
  laravel:
#    image: shingler/php7_laravel_nginx:v2
    image: laravel_dev:1.7
    restart: always
    depends_on:
      - mysql
    volumes:
      - /Users/shingler/project:/var/www
    container_name: my_laravel_dev
    ports:
      - 8100:8100
    expose:
      - 8100
    links:
      - "mysql:gf-mysql"
    networks:
      my_dev_workspace:
        ipv4_address: 172.17.0.2

  mysql:
    image: mysql:5.6
    restart: always
    volumes:
      - /var/lib/mysql
    container_name: mysql56
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      my_dev_workspace:
        ipv4_address: 172.17.0.3

  django:
    image: shingler/centos_python3_django:v1.2
    restart: always
    depends_on:
      - mysql
    volumes:
      - /Users/shingler/PycharmProjects:/var/www
    ports:
      - 8000:8000
    expose:
      - 8000
    container_name: my_django_nginx
    networks:
      my_dev_workspace:
        ipv4_address: 172.17.0.4

networks:
  my_dev_workspace:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.17.0.0/16
        gateway: 172.17.0.1

